# Generated by Django 2.2.11 on 2020-03-18 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='authors', to=settings.AUTH_USER_MODEL, verbose_name='followers'),
        ),
    ]
